apiVersion: v1
kind: Namespace
metadata:
  creationTimestamp: null
  name: nikita-jk-deploy
spec: {}
status: {}
---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nikita-webapp
  name: nikita-webapp
  namespace: nikita-jk-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nikita-webapp
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nikita-webapp
    spec:
      containers:
      - image: nikita213/nikita-cloud4c-app
        name: ashu-cloud4c-app
        ports:
        - containerPort: 80
        resources: {}
status: {}
---
apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: nikitalb1
  name: nikitalb1
  namespace: nikita-jk-deploy
spec:
  ports:
  - name: 1234-80
    port: 1234
    protocol: TCP
    targetPort: 80
  selector:
    app: nikita-webapp
  type: NodePort
status:
  loadBalancer: {}
